sudo: required
services:
  - docker
langauge: generic

before_install:
  - docker build -t jinwkim/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jinwkim/docker-react yarn test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-134397115302"
  bucket_path: "docker-react"
  on:
    branch: master
  
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"